/* Generated By:JJTree: Do not edit this line. ASTSUBTRACT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wci.intermediate.icodeimpl.ICodeNodeImpl,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wci.frontend;

public
class ASTSUBTRACT extends SimpleNode {
  public ASTSUBTRACT(int id) {
    super(id);
  }

  public ASTSUBTRACT(CdbParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CdbParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=81c9c65fbe1ff5b66c0a7e33ff288671 (do not edit this line) */
